import type { Post, ScheduledPost, Character, Note, DashboardStats } from './types';

export const dummyStats: DashboardStats = {
  totalPosts: 142,
  totalLikes: 8_420,
  totalImpressions: 312_500,
  avgEngagementRate: 4.2,
  scheduledCount: 7,
  followersGrowth: 12.5,
  changes: {
    totalPosts: null,
    totalLikes: null,
    totalImpressions: null,
    avgEngagementRate: null,
  },
};

export const dummyPosts: Post[] = [
  {
    id: '1',
    content: 'AIを使って毎日コンテンツを量産する仕組みを作ったら、フォロワーが3ヶ月で10倍になった話をします🧵\n\n最初は半信半疑でしたが、今では欠かせないワークフローになっています。',
    status: 'published',
    publishedAt: '2026-04-06T09:00:00Z',
    likes: 1240,
    retweets: 387,
    impressions: 45200,
    replies: 89,
    tags: ['AI', 'コンテンツ', 'フォロワー増加'],
    characterId: 'char-1',
  },
  {
    id: '2',
    content: '【朝活ルーティン公開】\n\n5:00 起床\n5:15 瞑想 15分\n5:30 X投稿チェック\n6:00 AIで今日の投稿を生成\n6:30 スケジュール設定完了\n\n午前中に全部終わらせて、昼以降は本業に集中できます💪',
    status: 'published',
    publishedAt: '2026-04-05T06:30:00Z',
    likes: 876,
    retweets: 234,
    impressions: 28900,
    replies: 67,
    tags: ['朝活', 'ルーティン', '生産性'],
    characterId: 'char-1',
  },
  {
    id: '3',
    content: 'Xで稼ぐために絶対やるべきこと3選\n\n① ニッチを絞る\n② 毎日投稿する\n③ 濃い読者1000人を目指す\n\nフォロワー数より「誰がフォローしているか」が重要。',
    status: 'published',
    publishedAt: '2026-04-04T12:00:00Z',
    likes: 2134,
    retweets: 891,
    impressions: 89300,
    replies: 145,
    tags: ['X運用', '収益化', 'ノウハウ'],
    characterId: 'char-2',
  },
  {
    id: '4',
    content: 'ChatGPTに投稿を作ってもらうときのコツ：自分の「声」をシステムプロンプトに入れること。そうしないと、みんな同じような投稿になってしまう。',
    status: 'published',
    publishedAt: '2026-04-03T18:00:00Z',
    likes: 567,
    retweets: 123,
    impressions: 19800,
    replies: 34,
    tags: ['ChatGPT', 'プロンプト', 'AI活用'],
    characterId: 'char-1',
  },
  {
    id: '5',
    content: '正直に言います。最初の3ヶ月はほぼゼロでした。でも諦めなかった理由は「複利の法則」を信じていたから。今日の1投稿が未来の自分を助ける。',
    status: 'draft',
    likes: 0,
    retweets: 0,
    impressions: 0,
    replies: 0,
    tags: ['マインドセット', '継続', '成長'],
    characterId: 'char-2',
  },
];

export const dummyScheduledPosts: ScheduledPost[] = [
  {
    id: 'sched-1',
    user_id: null,
    generated_post_id: null,
    persona_id: 'char-1',
    content: '【今週の学び】\n\nX運用で一番効果があったのは「スレッド投稿」でした。1ツイートより10倍のリーチが取れます。\n\n今日から試してみてください。',
    scheduled_at: '2026-04-08T09:00:00Z',
    published_at: null,
    status: 'scheduled',
    tags: ['X運用', 'スレッド', 'ノウハウ'],
    x_post_id: null,
    x_post_url: null,
    created_at: '2026-04-07T00:00:00Z',
    updated_at: '2026-04-07T00:00:00Z',
  },
  {
    id: 'sched-2',
    user_id: null,
    generated_post_id: null,
    persona_id: 'char-1',
    content: 'フォロワー1000人達成しました🎉\n\nここまでの道のりで学んだこと全部まとめます。明日のスレッドをお楽しみに。',
    scheduled_at: '2026-04-08T19:00:00Z',
    published_at: null,
    status: 'scheduled',
    tags: ['マイルストーン', '感謝'],
    x_post_id: null,
    x_post_url: null,
    created_at: '2026-04-07T00:00:00Z',
    updated_at: '2026-04-07T00:00:00Z',
  },
  {
    id: 'sched-3',
    user_id: null,
    generated_post_id: null,
    persona_id: 'char-2',
    content: 'バズる投稿には共通点があります。\n\n・数字を使う\n・具体的なノウハウ\n・体験談ベース\n\nこの3つを組み合わせるだけで、エンゲージメントが3倍になりました。',
    scheduled_at: '2026-04-09T12:00:00Z',
    published_at: null,
    status: 'scheduled',
    tags: ['バズ投稿', 'ノウハウ'],
    x_post_id: null,
    x_post_url: null,
    created_at: '2026-04-07T00:00:00Z',
    updated_at: '2026-04-07T00:00:00Z',
  },
];

export const dummyCharacters: Character[] = [
  {
    id: 'char-1',
    user_id: null,
    name: 'テック起業家キャラ',
    avatar: '🚀',
    tone: 'カジュアル・前向き',
    style: '体験談ベース、数字を使う、短文を多用',
    keywords: ['AI', '副業', '生産性', '自動化', '稼ぐ'],
    description: 'テクノロジーを使って生活を豊かにする方法を発信するキャラクター。体験談を交えながら、実践的なノウハウを届ける。',
    is_active: true,
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'char-2',
    user_id: null,
    name: 'マーケター視点キャラ',
    avatar: '📊',
    tone: 'プロフェッショナル・データドリブン',
    style: '分析的、箇条書き多用、根拠を示す',
    keywords: ['マーケティング', 'X運用', 'コンテンツ', '収益化', '分析'],
    description: 'データと実績をベースにSNSマーケティングのノウハウを発信。再現性の高い方法論を提供する。',
    is_active: false,
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
];

export const dummyNotes: Note[] = [
  {
    id: 'note-1',
    title: 'バズった投稿のパターン分析',
    content: '## バズる投稿の共通点\n\n1. **冒頭3行で引き込む** - スクロールを止める一文が必要\n2. **数字を使う** - 「3倍」「10分」「1000人」など具体的な数字\n3. **体験談ベース** - 「私が実際にやった結果」が反応を生む\n4. **行動を促す** - 最後に「あなたはどう思いますか？」など\n\n## NGパターン\n- 抽象的すぎる内容\n- 自慢だけで終わる\n- CTA（行動喚起）がない',
    tags: ['バズ分析', 'ノウハウ', '参考'],
    createdAt: '2026-04-01T10:00:00Z',
    isImportant: true,
  },
  {
    id: 'note-2',
    title: '最適な投稿時間帯メモ',
    content: '## 調査結果（自分のアカウント分析）\n\n- **7:00-8:00** → 通勤時間、インプレッション高い\n- **12:00-13:00** → 昼休み、エンゲージメント最高\n- **21:00-22:00** → 帰宅後リラックス、拡散されやすい\n\n**土日は11:00がピーク**\n\n週3回は夜の投稿を入れること。',
    tags: ['投稿時間', 'アナリティクス'],
    createdAt: '2026-04-02T14:00:00Z',
    isImportant: false,
  },
  {
    id: 'note-3',
    title: 'AIプロンプトのベストプラクティス',
    content: '## 使えるプロンプトテンプレート\n\n```\nあなたは[キャラクター設定]です。\n以下のトピックについて、[文字数]文字以内でX投稿を作成してください。\n\nトピック: [内容]\nトーン: [カジュアル/フォーマル]\n目的: [認知拡大/エンゲージメント向上/フォロワー増加]\n```\n\n## コツ\n- 具体的な制約を与えるほど品質が上がる\n- 過去のバズった投稿を参考例として与える\n- 複数パターン生成して選ぶ',
    tags: ['AIプロンプト', 'ChatGPT', 'ノウハウ'],
    createdAt: '2026-04-03T09:00:00Z',
    isImportant: true,
  },
];

export const dummyActivityFeed = [
  { id: 1, type: 'like', message: '「AIで毎日コンテンツを量産...」が1,240いいねを獲得', time: '2時間前', icon: '❤️' },
  { id: 2, type: 'schedule', message: '明日9:00の投稿をスケジュール設定しました', time: '4時間前', icon: '📅' },
  { id: 3, type: 'publish', message: '「フォロワー1000人達成...」を投稿しました', time: '6時間前', icon: '✅' },
  { id: 4, type: 'generate', message: 'AIで3件の投稿案を生成しました', time: '8時間前', icon: '🤖' },
  { id: 5, type: 'retweet', message: '「Xで稼ぐために...」が891RTを突破', time: '1日前', icon: '🔁' },
];
